export enum UserRole {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_STORE_ADMIN = 'ROLE_STORE_ADMIN',
  ROLE_CASHIER = 'ROLE_CASHIER',
  ROLE_BRANCH_MANAGER = 'ROLE_BRANCH_MANAGER',
  ROLE_STORE_MANAGER = 'ROLE_STORE_MANAGER',
}